font_family Hasklug Nerd font 
font_size 15

#cursor_shape beam
cursor_trail 1
cursor #ff79c6
confirm_os_window_close 0
#shell fish
background #1e1e2e


color4 #3985ff
color12 #89b4fa
color5 #7300ff
color13 #cba6f7
color6 #00bfff
color14 #94e2d5
color7 #ffffff
color15 #a6adc8
color0 #1c1d20
color8 #585b70
color1 #ff0048
color9 #f38ba8
color2 #15ff00
color10 #a6e3a1
color3 #ffca56
color11 #f9e2af
